0s
Run # 1. Extract root project name from settings.gradle or settings.gradle.kts
/home/runner/work/_temp/cdc82e10-f291-4830-9095-8eb9c6ddc6ff.sh: line 21: syntax error near unexpected token `<'
Error: Process completed with exit code 2.
